version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "daily-vaccine-totals"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dn9trgvzmu0k"
s3_prefix = "daily-vaccine-totals"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
